### PR TITLE
Fixed https support

### PR DESCRIPTION
**Pull request by falling-springs**
Fixed support for https by providing https scheme alongside domain when creating client.

### CODE REVIEW

**Comment by lmangani** [comment]
Thanks for the contribution and welcome to the group @falling-springs 
LGTM @ahuarte47 could you co-review approve this PR?

**Review by ahuarte47 — APPROVED** [review]
LGTM, thanks @falling-springs !

**Comment by falling-springs** [comment]
@lmangani Great, glad to help! FYI, I think the test failure during CI may be an intermittent issue with the httpbin site used in the SQL tests.  Looks like the server returned a 502: Bad Gateway error, which can't be parsed as JSON and so creates the error we see in the CI logs. It may be worth revising this test to use a different domain if this is a regular issue?

For now I think if you re-run that step it will likely pass

**Comment by ahuarte47** [comment]
Hi, sorry for this late message, this MR was great and it is working, but why not including always the `scheme` part in the client_url?

May I suggest a super simple change maybe in other new PR?

image

**Pull request merged**
